language: python

python: "3.6"
env:
  - TESTFOLDER=test_preprocess.py
  _ TESTFOLDER=test_preprocess.py
cache: pip
install: "pip install -r requirements.txt"
script: "$TESTFOLDER"

notifications:
  email:
    recipients:
      iel230@nyu.edu
    on_success: never
    on_failure: always

