language: python

jobs:
  include:
  - name: "preprocess"
  python: "3.6"
  cache: pip
  install: "pip install -r requirements.txt"
  script:  python test_preprocess.py
  -name: "pretrain"
  python: "3.6"
  cache: pip
  install: "pip install -r requirements.txt"
  script: python test_pretrain_VAE.py

notifications:
  email:
    recipients:
      iel230@nyu.edu
    on_success: never
    on_failure: always

