language: python
python:
  - "3.6"

cache: pip
install: "pip install -r requirements.txt"
env: 
  - TESTFOLDER=unit_tests/test_preprocess.py
  - TESTFOLDER=unit_tests/test_pretrain_VAE.py
script: "bundle exec rspec $TESTFOLDER"

notifications:
  email:
    recipients:
      iel230@nyu.edu
    on_success: never
    on_failure: always

