language: python

python: "3.6"
cache: pip
env:
  - TESTSUITE=test_process.py
  - TESTSUITE=test_process.py
install: "pip install -r requirements.txt"
script: "bundle exec rake test:$TEST_SUITE"

notifications:
  email:
    recipients:
      iel230@nyu.edu
    on_success: never
    on_failure: always

