language: python
python:
  - "3.6"

cache: pip
install: "pip install -r requirements.txt"
script: 
  - python unit_tests/test_preprocess.py
  - python unit_tests/test_pretrain_VAE.py

notifications:
  email:
    recipients:
      iel230@nyu.edu
    on_success: never
    on_failure: always

